name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-10.15
          - macos-latest
          - ubuntu-latest
        ocaml-compiler:
          - 4.13.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ensure `apt` is up to date
        run: sudo apt-get update
        if: contains(matrix.os, 'ubuntu')
          
      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: System dependencies
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            sudo apt-get install -y libgmp-dev python3
          elif [ "$RUNNER_OS" = "macOS" ]; then
            brew install gmp python3
            sudo mkdir -p /opt/local/lib
          else
            echo Unsupported OS: $RUNNER_OS
            exit 1
          fi          

      - name: OCaml dependencies
        run: opam install -y ocamlfind ppx_deriving batteries ANSIterminal fmt alcotest cmdliner logs zarith z3 dune
        
      - name: Build kmt and other executables
        run: opam exec -- dune build --display short -- src/kmt src/test_word src/test_equivalence src/run_eval

      - name: Word equivalence tests
        run: opam exec -- dune exec -- src/test_word

      - name: KMT equivalence tests
        run: opam exec -- dune exec -- src/test_equivalence

      - name: KMT evaluation
        run: opam exec -- dune exec -- src/run_eval

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker container
        run: docker build -t kmt .
