name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-10.15
          - macos-latest
          - ubuntu-latest
        ocaml-compiler:
          - 4.13.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: System dependencies
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            sudo apt-get install -y libgmp-dev python3
          elif [ "$RUNNER_OS" = "macOS" ]; then
            brew install gmp python3
            sudo mkdir -p /opt/local/lib
          else
            echo Unsupported OS: $RUNNER_OS
            exit 1
          fi          

      - name: Install via OPAM
        run: |
            opam install -t .
            eval $(opam env)
         
      - name: KMT evaluation
        run: opam exec -- kmt_eval

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker container
        run: docker build -t kmt .
